filter: ensure MapResult is followed for parent directories
Similar to the previous commit, we weren't properly respecting MapResult
return values for parent directories. To resolve this, we just store
into `skipFn` just like previously, and return `SkipDir` instead of
`continue`ing on.

After these changes, the new test passes, and we don't end up including
entries that were in excluded directories, as was happening before:

	Error:      	Not equal:
			expected: "dir y\nfile y/b.txt\n"
			actual  : "file x/a.txt\ndir y\nfile y/b.txt\n"

Signed-off-by: Justin Chadwell <me@jedevc.com>